-- AlterTable
ALTER TABLE `card` ADD COLUMN `couponId` VARCHAR(191) NOT NULL DEFAULT '9a950c39-5b33-4736-9ec0-f3bd0e110534';

-- AddForeignKey
ALTER TABLE `Card` ADD CONSTRAINT `Card_couponId_fkey` FOREIGN KEY (`couponId`) REFERENCES `Coupon`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
